server:
  port: 9005
  servlet:
    context-path: /

spring:
  application: 
    name: dart-cart

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://paglipay-postgres.postgres.database.azure.com:5432/postgres?currentSchema=public
    username: paglipay@paglipay-postgres
    password: PAssw0rd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
#  
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    #<login user to smtp server>
#    username: noreplydartcart@gmail.com
#    #<login password to smtp server>
#    password: RevatureP3pass45
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"

com.example.server.jwtissuer : localhost
com.example.server.secret : aa2228b097e40541dfb229bacf40f00a81eac92a1b11412c4d678cb99feba0e96187db65b4b28eefd90097aa3b668790189dc1635823b7bb44cc5b4abdc61c37
